export const cartTypes = {
  ADD_PRODUCT_TO_CART_REQUEST: '@cart/ADD_PRODUCT_TO_CART_REQUEST',
  ADD_PRODUCT_TO_CART_SUCCESS: '@cart/ADD_PRODUCT_TO_CART_SUCCESS',
  ADD_PRODUCT_TO_CART_FAILURE: '@cart/ADD_PRODUCT_TO_CART_FAILURE',
  REMOVE_PRODUCT_FROM_CART: '@cart/REMOVE_PRODUCT_FROM_CART'
}
